# =========================
# GENERAL
# =========================
TLP_DEFAULT_MODE=AC
TLP_PERSISTENT_DEFAULT=1

# =========================
# NVME
# =========================
NVME_APST_ON_AC=1
NVME_APST_ON_BAT=1

DISK_IDLE_SECS_ON_AC=0

# =========================
# WIFI
# =========================
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=2

# =========================
# SOUND
# =========================
SOUND_POWER_SAVE_ON_AC=0

# =========================
# PCIe
# =========================
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=powersave

# =========================
# RUNTIME PM
# =========================
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto

# =========================
# USB
# =========================
USB_AUTOSUSPEND=0

# =========================
# GPU (RADEON)
# =========================
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=performance
RADEON_DPM_PERF_LEVEL_ON_AC=high
RADEON_DPM_PERF_LEVEL_ON_BAT=auto
AMDGPU_ABM_LEVEL_ON_AC=0

# =========================
# CPU
# =========================
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=schedutil

CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power

CPU_BOOST_ON_AC=0
CPU_BOOST_ON_BAT=0

SCHED_POWERSAVE_ON_AC=0

MAX_LOST_WORK_SECS_ON_AC=0

# =========================
# PLATFORM PROFILE
# =========================
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=balanced
